### ISSUE TITLE
MasterVyrn 1.0 Roadmap

### ISSUE THREAD

**Issue by miaulightouch** [LightouchDev/MasterVyrn#15]
Since the basic code base is stable now (probably), maybe I can start this roadmap now.

- [ ] [GBF-Raiders](https://github.com/ypinskiy/GBF-Raiders) Integration
- [ ] General features
  - [ ] AP notification
  - [ ] EP notification
  - [ ] Daily reset notification
  - [ ] Strike time notification
  - [ ] Screen capture
    - help to show off your new SSR to your friends
  - [ ] Browser default font override option
    - the font rendering in windows is **GOD DAMN UGLY** with default CJK fonts, this allow player choose font for rendering.
- [ ] Add feature from [Ancheera](https://github.com/Thessiah/Ancheera)
  - [ ] Player dashboard
  - [ ] Raids progress list
  - [ ] Supply list
  - [ ] Crafting planner
- [ ] Add feature from [Viramate](https://chrome.google.com/webstore/detail/viramate/fgpokpknehglcioijejfeebigdnbnokj)
  - [ ] Quest/Raid list
  - [ ] Keep play sound when window lost focus
  - [ ] Improve combat UI
    - **without modifying game**
- [ ] Keyboard controll
- [ ] Gamepad controll

It's quite a lot of works to do, but most important requirements is ready, It's able to fetch all necessary communications between server and client.

**Comment by miaulightouch** [comment]
基本的程式碼已經穩定了（大概），或許現在已經可以揭露 1.0 的開發方向

- [ ] [GBF-Raiders](https://github.com/ypinskiy/GBF-Raiders) 整合
- [ ] 一般功能
  - [ ] AP 通知
  - [ ] BP 通知
  - [ ] 每日重置通知
  - [ ] 追擊時段(AT)通知
  - [ ] 螢幕截圖
    - 幫助你快速曬卡
  - [ ] 瀏覽器預設字體設定
    - Windows 內建的 CJK 字體 **他媽真心醜**，允許玩家使用個人偏好的字體。
- [ ] 加入來自 [Ancheera](https://github.com/Thessiah/Ancheera) 的功能
  - [ ] 玩家資訊總覽
  - [ ] 副本進度列表
  - [ ] 持有物品清單
  - [ ] 物品製作進度預覽
- [ ] 加入來自 [Viramate](https://chrome.google.com/webstore/detail/viramate/fgpokpknehglcioijejfeebigdnbnokj) 的功能
  - [ ] 任務/副本列表
  - [ ] 視窗失焦時仍持續播放音效
  - [ ] 加強戰鬥 UI
    - **不修改遊戲本體**
- [ ] 鍵盤操作支援
- [ ] 搖桿操作支援

看起來雖然有非常多目標要達成，但上述功能的基礎已完成。目前已經可以從伺服器到遊戲之間擷取任何所需的資訊。
